name: CI

on:
  push:          # main / develop への push
    branches: [main, develop]
  pull_request:  # すべての PR

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]     # 必要なら 18.x などを追加

    steps:
      # 1. ソースを取得
      - uses: actions/checkout@v4

      # 2. Node をセットアップし、npm の依存キャッシュを有効化
      - uses: actions/setup-node@v4      # v4 系は Node 20 実行基盤に更新済み :contentReference[oaicite:0]{index=0}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'                  # npm の依存ファイルを自動キャッシュ :contentReference[oaicite:1]{index=1}

      # 3. パッケージをクリーンインストール
      - name: Install dependencies
        run: npm ci                     # lockfile (package-lock.json) 前提

      # 4. ESLint（lint スクリプトが存在）
      - name: Run ESLint
        run: npm run lint

      # 5. テスト（test スクリプトがある場合のみ実行）
      - name: Run tests
        run: npm run --if-present test -- --ci

      # 6. ビルド
      - name: Build Next.js
        run: npm run build